#theme: jekyll-theme-cayman
title: AzureCP
tagline: Claims provider for SharePoint 2019 / 2016 / 2013 and Azure Active Directory
#paginate: 1
show_downloads: true
repository: Yvand/AzureCP
timezone: Europe/Paris

# About/contact
author:
  name:       Yvan Duhamel
  url:        https://www.linkedin.com/in/yvand/

# Gems
plugins:
 # - jekyll-paginate
  - jekyll-sitemap

#Others
markdown: kramdown