#theme: jekyll-theme-cayman
#title: AzureCP
tagline: Azure Active Directory claims provider for SharePoint 2013 and 2016
#paginate: 1
show_downloads: true
repository: Yvand/AzureCP
timezone: Europe/Paris

# About/contact
author:
  name:       Yvan Duhamel
  url:        https://www.linkedin.com/in/yvand/

# Gems
plugins:
 # - jekyll-paginate
  - jekyll-sitemap

#Others
markdown: kramdown