resources:
- repo: self

jobs:
- job: CreateTestEnvironment
  displayName: Create test environment
  timeoutInMinutes: 90
  pool:
    vmImage: 'windows-2019'
  steps:
  - checkout: none #skip checking out the default repository resource
  - task: ms-azuredevtestlabs.tasks.azure-dtl-task-createEnvironment.AzureDevTestLabsCreateEnvironment@1
    displayName: 'Create Azure DevTest Labs Environment'
    inputs:
      ConnectedServiceName: '$(DevTestLabs.AzureConnectionName)'
      LabId: '/subscriptions/$(DevTestLabs.AzureSubscriptionId)/resourceGroups/$(DevTestLabs.LabName)/providers/Microsoft.DevTestLab/labs/$(DevTestLabs.LabName)'
      RepositoryId: '/subscriptions/$(DevTestLabs.AzureSubscriptionId)/resourcegroups/$(DevTestLabs.LabName)/providers/microsoft.devtestlab/labs/$(DevTestLabs.LabName)/artifactsources/$(DevTestLabs.RepoID)'
      TemplateId: '/subscriptions/$(DevTestLabs.AzureSubscriptionId)/resourceGroups/$(DevTestLabs.LabName)/providers/Microsoft.DevTestLab/labs/$(DevTestLabs.LabName)/artifactSources/$(DevTestLabs.RepoID)/armTemplates/SharePoint-ADFS-DevTestLabs'
      EnvironmentName: 'Tests-$(system.teamProject)'
      ParameterOverrides: "-location '$(Deployment.Location)' -provisionSharePoint2013 '$(Deployment.ProvisionSharePoint2013)' -provisionSharePoint2016 '$(Deployment.ProvisionSharePoint2016)' -provisionSharePoint2019 '$(Deployment.ProvisionSharePoint2019)' -enableHybridBenefitServerLicenses 'Yes' -adminUserName '$(Deployment.AdminUserName)' -adminPassword '$(Deployment.AdminPassword)' -serviceAccountsPassword '$(Deployment.ServiceAccountsPassword)'"
      TemplateOutputVariables: true
      ExportEnvironmentTemplate: true
    timeoutInMinutes: 90
